name: Multi-Agent GenAI Knowledge Navigator CI/CD with GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/knowledge-navigator-rag

jobs:
  docker_build_and_push:
    name: Build & Push Docker Image to GHCR
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deployment
        run: echo "Deploying to environment (Kubernetes, ECS, etc.)..."
